name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  call-continuous-integration:
    uses: levigo/reusable-workflows/.github/workflows/continuous-integration.yml@v3
    secrets: inherit
    with:
      mattermostChannel: 'neverpile-ci'
      matrix: '{"jdk": [17]}'
      timeoutMinutes: 5
