name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  call-continuous-integration:
    uses: levigo/reusable-workflows-pub/.github/workflows/continuous-integration.yml@v1
    secrets: inherit
    with:
      mattermostChannel: 'neverpile-ci'
      matrix: '{"jdk": [17]}'
      timeoutMinutes: 5
